swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '2.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

# Accounts
  /user/accounts:
    get:
      security:
        - Bearer: []
      tags:
        - User Accounts
      summary: List of user Acounts API
      description: API for fetching list of accounts
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: List of accounts retrieved successully
          schema:
            $ref: '#/definitions/GetAccountList'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/accounts/{accountId}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - User Accounts
      summary: List of account transactions API
      description: API for fetching list of account transactions 
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Numeric ID of the account to get
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions retrieved successully
          schema:
            $ref: '#/definitions/GetTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#Create new transaction
    post:
      security:
        - Bearer: []
      tags:
        - User Accounts
      summary: Create Transaction API
      description: API for creating a new transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Numeric ID of the account to get
          required: true
        - in: body
          name: body
          description: Create a new transaction
          required: true
          schema:
            $ref: "#/definitions/PostTransaction"
      produces:
        - application/json
      responses:
        '200':
          description: The transaction was successfully created
          schema:
            $ref: '#/definitions/GetTransaction'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

 #Update a transaction
  /user/accounts/{accountId}/transactions/{transactionId}:
    patch:
      security:
        - Bearer: []
      tags:
        - User Accounts
      summary: Update Transaction API
      description: API for updating a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: number
          description: Numeric ID of the account to get
          required: true
        - in: path
          name: transactionId
          type: number
          description: Numeric ID of the transaction to get
          required: true
        - in: body
          name: body
          description: Update a transaction
          required: true
          schema:
            $ref: "#/definitions/PatchTransaction"
      responses:
          '200':
            description: The transaction was successfully updated
            schema:
              $ref: '#/definitions/GetTransaction'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error

  # 
  # 
  # V2
  /user/accounts/transactions?accountId={accountId}:
    get:
      security:
        - Bearer: []
      tags:
        - User Accounts v2
      summary: List of account transactions API
      description: API for fetching list of account transactions 
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Numeric ID of the account to get
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: List of transactions retrieved successully
          schema:
            $ref: '#/definitions/GetTransactionV2'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    
  # #Create new transaction
  # /user/accounts/transactions?accountId={accountId}&transactionId={transactionId}:
  #   post:
  #     security:
  #       - Bearer: []
  #     tags:
  #       - User Accounts v2
  #     summary: Create Transaction API
  #     description: API for creating a new transaction
  #     parameters:
  #       - in: header
  #         type: string
  #         name: Authorization
  #         description: Attach Bearer JWT token
  #         required: true
  #       - in: path
  #         name: accountId
  #         type: string
  #         description: Numeric ID of the account to get
  #         required: true
  #       - in: body
  #         name: body
  #         description: Create a new transaction
  #         required: true
  #         schema:
  #           $ref: "#/definitions/PostTransaction"
  #     produces:
  #       - application/json
  #     responses:
  #       '200':
  #         description: The transaction was successfully created
  #         schema:
  #           $ref: '#/definitions/GetTransaction'
  #       '400':
  #         description: Invalid Fields
  #       '500':
  #         description: Internal Server Error

#Create new transaction
  /user/accounts/{accountId}/transaction:
    post:
      security:
        - Bearer: []
      tags:
        - User Accounts v2
      summary: Create Transaction API
      description: API for creating a new transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: string
          description: Numeric ID of the account to get
          required: true
        - in: body
          name: body
          description: Create a new transaction
          required: true
          schema:
            $ref: "#/definitions/PostTransactionV2"
      produces:
        - application/json
      responses:
        '200':
          description: The transaction was successfully created
          schema:
            $ref: '#/definitions/GetTransactionV2'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

#  Update a transaction
  /user/accounts/{accountId}/transaction/{transactionId}:
    patch:
      security:
        - Bearer: []
      tags:
        - User Accounts v2
      summary: Update Transaction API
      description: API for updating a transaction
      parameters:
        - in: header
          type: string
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: accountId
          type: number
          description: Numeric ID of the account to get
          required: true
        - in: path
          name: transactionId
          type: number
          description: Numeric ID of the transaction to get
          required: true
        - in: body
          name: body
          description: Update a transaction
          required: true
          schema:
            $ref: "#/definitions/PatchTransaction"
      responses:
          '200':
            description: The transaction was successfully updated
            schema:
              $ref: '#/definitions/GetTransactionV2'
          '400':
            description: Invalid Fields
          '500':
            description: Internal Server Error

# Models
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string

  GetAccountList:
    type: object
    properties: 
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accounts:
            type: array
            items:
              properties:
                accountId:
                  type: integer
                  description: Account id
                description:
                  type: string
                  description: Account description
                amount:
                  type: number
                  format : float
                  description: Account amount in $
                balance : 
                  type : string
                  description: Account balance status

  GetTransaction:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          accountId:
            type: integer
            description: Account id associated with the transactions
          transactions:
            type: array
            items:
              properties:
                transactionId:
                  type: integer
                  description: Transaction id
                date:
                  type: string
                  format: date-type
                  description: Transaction date
                description:
                  type: string
                  description: Transaction name
                amount:
                  type: number
                  format : float
                  description: Amount in $
                balance : 
                  type: number
                  format : float
                  description: account balance status
                type :
                  type: string
                  description: Transaction type
                category:
                  type: string
                  description: Transaction category
                notes:
                  type: string
                  description: Transaction category

# V2
  GetTransactionV2:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transactions:
            type: array
            items:
              properties:
                accountId:
                  type: integer
                  description: Account id associated with the transactions
                transactionId:
                  type: integer
                  description: Transaction id
                date:
                  type: string
                  format: date-type
                  description: Transaction date
                description:
                  type: string
                  description: Transaction name
                amount:
                  type: number
                  format : float
                  description: Amount in $
                balance : 
                  type: number
                  format : float
                  description: account balance status
                type :
                  type: string
                  description: Transaction type
                category:
                  type: string
                  description: Transaction category
                notes:
                  type: string
                  description: Transaction category
  
  
  PostTransaction:
    type: object
    properties:
      transactionId:
        type: integer
      date:
        type: string
        format: date-type
        description: Transaction date
      description:
        type: string
        description: Transaction name
      amount:
        type: number
        format : float
        description: Amount in $
      balance : 
        type: number
        format : float
        description: account balance status
      type :
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      notes:
        type: string
        description: Transaction category

  # V2
  PostTransactionV2:
    type: object
    properties:
      accountId:
        type: integer
        description: Account id associated with the transactions
      transactionId:
        type: integer
      date:
        type: string
        format: date-type
        description: Transaction date
      description:
        type: string
        description: Transaction name
      amount:
        type: number
        format : float
        description: Amount in $
      balance : 
        type: number
        format : float
        description: account balance status
      type :
        type: string
        description: Transaction type
      category:
        type: string
        description: Transaction category
      notes:
        type: string
        description: Transaction category
       
  PatchTransaction:
    type: object
    properties:
      category :
        type : string
      notes : 
        type : string